#! /bin/sh

BENCH_DIR=
if [ -d "$1" ]; then
    BENCH_DIR="$1"
else
    echo "usage: $0 <dir>"
    exit 2
fi

TIME="`which time` --verbose"

echo "Find  + md5sum"
$TIME find $BENCH_DIR -type f -exec md5sum {} \; > /tmp/benchfindmd5

echo "Dircmp"
$TIME dircmp digest -parse-tree $BENCH_DIR -save-to /tmp/benchdircmp

ls -lh /tmp/bench*

